name: Sensorium Pictures
favicon: null
layout_spectrum: 0.8802
typography_spectrum: 0.55068
title: 'SENSORIUM Pictures '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d0c4b6'
    - '#e31f43'
    - '#34a8a5'
    - '#bdeded'
    - '#ed5a78'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
