name: Sensorium Pictures
favicon: null
layout_spectrum: 1
typography_spectrum: 0.55068
title: 'Sensorium Pictures - bringing each element of the story together, in every sense of the word. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0c1921'
    - '#926850'
    - '#bfbaa7'
    - '#89201a'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
