name: Sensorium Pictures
favicon: null
layout_spectrum: 0.90937
typography_spectrum: 1
title: 'SENSORIUM Pictures '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#220e19'
    - '#bd9128'
    - '#984d64'
    - '#e3c57d'
    - '#feffff'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
