name: Sensorium Pictures
favicon: null
layout_spectrum: 0.8802
typography_spectrum: 0.55068
title: 'SENSORIUM Pictures '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010006'
    - '#6ef9cc'
    - '#35927b'
    - '#ab2b09'
    - '#d3cc8f'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
